version: "3.3"
services:
  server:
    build: ./server
    depends_on:
      - mysql
    env-file: .env
    ports:
      - 8000:8000
    links:
      - db
    command: yarn start
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'



