version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks: 
      - backend 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.ml.enabled=false
    # privileged: true
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    networks:
      - backend
    ports:
      - 9200:9200
      - 9300:9300
  server:
    build: .
    container_name: server
    depends_on:
      - db
      - elasticsearch
    ports:
      - 3000:3000
    command: bash -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && node init/esMappings.js && yarn start"
    networks: 
      - backend
    restart: always
networks: 
  backend:
volumes:
  logs:
  esdata:



