version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks: 
      - backend 
  server:
    build: .
    container_name: server
    depends_on:
      - db
    ports:
      - 3000:3000
    command: bash -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && yarn start"
    networks: 
      - backend
    restart: always
networks: 
  backend:



